apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgBhftELhxlnx49W+tczZ1kpfomtxd2Eo39ZroWNSo03qD4eER+sIHNlWUy7UTxgiO+NEEc/sYVQvYysKUD9EbfU+f0RPneEdECyw+6eAwzJI4d+l7keJEn+ldLsRMrNVkt9F0FTlhUXnJOQXMgAn9+P9Le5VJdGGYpLErfRsaw6gZ9KtEEp50GO7t+XELs/tWLMzj0+5rndSDYiS589o3PZMxUJ+JOyt1boYjlcz9lFW2hBdDRldaEDgwrOY5j7KVHhnLui7XDxP5eI6gdlXf5/P6F3HW9M2sv/O34kOFcoV7N4Ky63O1oVk6s6ZL3Y8j3di431R6pVPkfjOQPxZeIi3j0PflfV1U4yroIME2tbs7DIctL3WygeS5lKlJYLVZMTBOMM638DWfgUOf8IANGlCRF2eiinlaKN3QFMcwjr5NI5T/bH1KivwKBFaxgWl3IUIKQ5Qa6dZ1/OMsNed8AekZdheHryFw6pve5yE2S/PA5ZTPLiQGJKRgSg0AeFNIq9CzeAjKw+90VH/RcR3rpJK1ThSj469j+YUMZgdhKd+Ru0Z5DU/RvWADkZLifnKQykiv9bBi5qENArrpxXCzhXG8kQKsIGb3qeg1Jbkfk6plHczBWLPQDhvpIn/00KSMQOGjtQDW0NggatWP+9q7PGHx/FTIngOiU8vQJZA4RsY3kUThWeRWBXQpeth8t+GcvA75pNWtwT9vK9sA==
    username: AgA/MA0fUX+UwyIC0wQJAc38n3Cobht5/KU1krds0PkdQWLqzrIaOo1MdDr4jWtvtJXCIv8Bing//cV4jkh4hsW8bVj4c+dMf8sW2iGQaENEoTXLjUbb7laavysm167w9URZIlKlMGC2RSmKUrRAPwedHQxgLuXfcdoC3+EIV2cCbZbG8YN6ruCIJGOMocw7sOWNCiF63qYVcb/+/CHJD66w25ei0/c68pBiQXAJwmmw4zSIknrEbL5+rlxqd7HvArVbMiz+vLBGEOtdhkmeIw0fmdnRFrROCzNviLXx5tGmxa48SwX5nZE8czQi1F3ux9kYN8DExl78c6dPCAM2XviEvTL/YFridlehc1zeUxvpx0eY4yxo9+jOOidFJyWTvvhPWrv/O/v1EzDYlEQY+WN7gGLb/E5CTTbp6KMxEyr9BoTUQIPKsknaukRGoPS6nJ2I/K151PGkgQlVCk9B+DSidvgIMTMwTbZ97f4wAWSW5F1v/KSPbwKRd+C6v9Myi7rgd+3QHSwDy5Ft/CEqpqt1UaF7579Nf2ESaR5qgo2513IElldTaQV5w+mWUuv7N03JWN+gSjg0cIQKugo5aUGBivyW9OjG/Z96juj+gvPrMH1BkKTiiUvRtXJWPE0dmQKUgyTcLsRb2PtBLaC7YG2aLZTc+hdxI1Tg3UnIxM3jjo/Aq8vw2LGCUGh93nHGqxc0CVVlMpNWpAw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

